version: "3.8"

services:
  mysql:
    image: mysql:8.0.23
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mysql
    networks:
      - mysql-network
      - dev
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   container_name: phpmyadmin
  #   ports:
  #     - 5001:80
  #   environment:
  #     - PMA_HOST=mysql
  #     - PMA_USER=root
  #     - PMA_PASSWORD=root
  #     - PMA_NAME=mysql
  #   depends_on:
  #     - mysql
  #   networks:
  #     - mysql-network

  www:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: web
    restart: unless-stopped
    ports:
      - "8000:80"
    command:
      [
        "/wait-for-it.sh",
        "mysql:3306",
        "--",
        "/docker-entrypoint.sh"
      ]
    environment:
      - APP_ENV=dev
      - APP_DEBUG=true
      - APP_URL=http://46.101.35.94:8000/
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=mysql
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - DATABASE_URL=mysql://root:root@mysql:3306/thetiptop
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - dev
      - mysql-network

networks:
  mysql-network:
    driver: bridge
  dev:
    driver: bridge