version: "3.8"

services:
  mysql:
    image: mysql:8.0.23
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mysql
    networks:
      - mysql-network

  

networks:
  mysql-network:
    name: "mysql-network"
    external: true
