version: "3.8"

services:
  preprod_web_thetiptop:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    image: preprod_thetiptop
    container_name: preprod_web_thetiptop
    restart: unless-stopped
    command:
      [
        "/wait-for-it.sh",
        "mysql:3306",
        "--",
        "/docker-entrypoint.sh"
      ]
    ports:
      - "8001:80"
    environment:
      - APP_ENV=dev
      - APP_DEBUG=false
      - APP_URL=https://preprod.dsp-archiwebf22-eb-we-fh.fr/
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=mysql
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - BROADCAST_DRIVER=log
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - DATABASE_URL=mysql://root:root@mysql:3306/thetiptop-prod
    labels:
      - traefik.enable=true
      - traefik.http.routers.preprod_web_thetiptop.rule=Host(`preprod.dsp-archiwebf22-eb-we-fh.fr`)
      - traefik.http.routers.preprod_web_thetiptop.entrypoints=websecure
      - traefik.http.routers.preprod_web_thetiptop.tls=true
      - traefik.http.routers.preprod_web_thetiptop.tls.certresolver=letsencrypt
      - traefik.http.services.preprod_web_thetiptop.loadbalancer.server.port=80
      - traefik.docker.network=traefik
    networks:
      - mysql-network
      - traefik

networks:
  mysql-network:
    name: "mysql-network"
    external: true
  traefik:
    external: true